# frozen_string_literal: true

# Code generated by Scalar SDK Generator. DO NOT EDIT.
require "json"
require "stringio"
require "time"

root = File.exist?(File.join(__dir__, "lib", "galaxy-ruby.rb")) ? __dir__ : File.expand_path("..", __dir__)
$LOAD_PATH.unshift(File.join(root, "lib"))
require "galaxy-ruby"

# Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
# Run it from this repo with `ruby tests/smoke-test.rb`. The generator also runs this file
# against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
client = ScalarGalaxy::Client.new(max_retries: 0, timeout: 30)

cases = [
  {
    operation: "create",
    method: "POST",
    path: "/planets",
    label: "required params",
    run: -> { client.planets.create({id: 1, name: "Mars"}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/planets",
    label: "all params",
    run: -> do
      client.planets.create(
        {
          id: 1,
          name: "Mars",
          atmosphere: [],
          creator: {
            "name" => "Marc"
          },
          description: "The red planet",
          discovered_at: "1610-01-07T00:00:00Z",
          failure_callback_url: "https://example.com/webhook",
          habitability_index: 0.68,
          image: "https://cdn.scalar.com/photos/mars.jpg",
          last_updated: "2024-01-15T14:30:00Z",
          physical_properties: {
            "mass" => 0.107,
            "radius" => 0.532,
            "gravity" => 0.378,
            "temperature" => {}
          },
          satellites: [],
          success_callback_url: "https://example.com/webhook",
          tags: [],
          type: "terrestrial"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/planets/{planetId}",
    run: -> { client.planets.retrieve(1) }
  },
  {
    operation: "update",
    method: "PUT",
    path: "/planets/{planetId}",
    label: "required params",
    run: -> { client.planets.update(1, {id: 1, name: "Mars"}) }
  },
  {
    operation: "update",
    method: "PUT",
    path: "/planets/{planetId}",
    label: "all params",
    run: -> do
      client.planets.update(
        1,
        {
          id: 1,
          name: "Mars",
          atmosphere: [],
          creator: {
            "name" => "Marc"
          },
          description: "The red planet",
          discovered_at: "1610-01-07T00:00:00Z",
          failure_callback_url: "https://example.com/webhook",
          habitability_index: 0.68,
          image: "https://cdn.scalar.com/photos/mars.jpg",
          last_updated: "2024-01-15T14:30:00Z",
          physical_properties: {
            "mass" => 0.107,
            "radius" => 0.532,
            "gravity" => 0.378,
            "temperature" => {}
          },
          satellites: [],
          success_callback_url: "https://example.com/webhook",
          tags: [],
          type: "terrestrial"
        }
      )
    end
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/planets/{planetId}",
    run: -> { client.planets.delete(1) }
  },
  {
    operation: "delteImage",
    method: "POST",
    path: "/planets/{planetId}/image",
    label: "required params",
    run: -> { client.planets.delte_image(1) }
  },
  {
    operation: "delteImage",
    method: "POST",
    path: "/planets/{planetId}/image",
    label: "all params",
    run: -> { client.planets.delte_image(1, {image: "@mars.jpg"}) }
  },
  {
    operation: "listAllData",
    method: "GET",
    path: "/planets",
    run: -> { client.planets.list_all_data({limit: 10, offset: 0}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/celestial-bodies",
    label: "required params",
    run: -> { client.celestial_bodies.create({celestial_body: {"name" => "Mars"}}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/celestial-bodies",
    label: "all params",
    run: -> do
      client.celestial_bodies.create(
        {
          celestial_body: {
            "name" => "Mars",
            "description" => "The red planet",
            "type" => "terrestrial",
            "habitabilityIndex" => 0.68,
            "physicalProperties" => {},
            "atmosphere" => [],
            "discoveredAt" => "1610-01-07T00:00:00Z",
            "image" => "https://cdn.scalar.com/photos/mars.jpg",
            "satellites" => [],
            "creator" => {},
            "tags" => [],
            "successCallbackUrl" => "https://example.com/webhook",
            "failureCallbackUrl" => "https://example.com/webhook"
          }
        }
      )
    end
  },
  {
    operation: "createToken",
    method: "POST",
    path: "/auth/token",
    run: -> { client.authentication.create_token({email: "marc@scalar.com", password: "i-love-scalar"}) }
  },
  {
    operation: "createUser",
    method: "POST",
    path: "/user/signup",
    run: -> do
      client.authentication.create_user({email: "marc@scalar.com", password: "i-love-scalar", name: "Marc"})
    end
  },
  {operation: "listMe", method: "GET", path: "/me", run: -> { client.authentication.list_me }}
]

def run_case(test_case)
  started_at = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  # `label` distinguishes the required-params run from the all-params run of the same operation;
  # it is absent entirely when the operation contributed only one case.
  identity = {operation: test_case[:operation], method: test_case[:method], path: test_case[:path]}
  identity[:label] = test_case[:label] if test_case[:label]
  begin
    test_case[:run].call
    identity.merge(
      status: "passed",
      durationMs: ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started_at) * 1000).to_i
    )
  rescue StandardError => e
    identity.merge(
      status: "failed",
      durationMs: ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started_at) * 1000).to_i,
      error: ([e.class.name, e.message] + e.backtrace.to_a).join("\n")
    )
  end
end

filter = ENV["SCALAR_SMOKE_FILTER"]
needles = filter ? filter.split(",").map(&:strip).reject(&:empty?) : []
selected =
  (
    if needles.empty?
      cases
    else
      cases.select do |test_case|
        needles.any? { |needle| test_case[:operation].include?(needle) || test_case[:path].include?(needle) }
      end
    end
  )

results =
  selected.map { |test_case| Thread.new(test_case) { |smoke_case| run_case(smoke_case) } }.map(&:value)

failed = results.select { |result| result[:status] == "failed" }
if ENV["SCALAR_SMOKE_REPORT"]
  File.write(
    ENV.fetch("SCALAR_SMOKE_REPORT"),
    JSON.generate({total: results.length, failed: failed.length, results: results})
  )
else
  results.each do |result|
    suffix = result[:label] ? " [#{result[:label]}]" : ""
    if result[:status] == "passed"
      puts "PASS #{result[:operation]}#{suffix} (#{result[:method]} #{result[:path]}) #{result[:durationMs]}ms"
    else
      warn "FAIL #{result[:operation]}#{suffix} (#{result[:method]} #{result[:path]})\n#{result[:error]}"
    end
  end
  warn "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing)." if results.empty?
  puts "\n#{results.length - failed.length}/#{results.length} samples passed" unless results.empty?
end

exit(1) if failed.any? || results.empty?
