module ScalarGalaxy
  module Models
    type authentication_create_token_params =
      {  } & ScalarGalaxy::Internal::Type::request_parameters

    class AuthenticationCreateTokenParams < ScalarGalaxy::Models::Credentials
      extend ScalarGalaxy::Internal::Type::RequestParameters::Converter
      include ScalarGalaxy::Internal::Type::RequestParameters

      def initialize: (?request_options: ScalarGalaxy::request_opts) -> void

      def to_hash: -> { request_options: ScalarGalaxy::RequestOptions }
    end
  end
end
