module ScalarGalaxy
  module Models
    type authentication_create_user_params =
      { email: String, password: String, name: String }
      & ScalarGalaxy::Internal::Type::request_parameters

    class AuthenticationCreateUserParams < ScalarGalaxy::Internal::Type::BaseModel
      extend ScalarGalaxy::Internal::Type::RequestParameters::Converter
      include ScalarGalaxy::Internal::Type::RequestParameters

      attr_accessor email: String

      attr_accessor password: String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        email: String,
        password: String,
        ?name: String,
        ?request_options: ScalarGalaxy::request_opts
      ) -> void

      def to_hash: -> {
        email: String,
        password: String,
        name: String,
        request_options: ScalarGalaxy::RequestOptions
      }
    end
  end
end
