module ScalarGalaxy
  module Models
    type credentials = { email: String, password: String }

    class Credentials < ScalarGalaxy::Internal::Type::BaseModel
      attr_accessor email: String

      attr_accessor password: String

      def initialize: (email: String, password: String) -> void

      def to_hash: -> { email: String, password: String }
    end
  end
end
