module ScalarGalaxy
  module Models
    type planet_create_params =
      {  } & ScalarGalaxy::Internal::Type::request_parameters

    class PlanetCreateParams < ScalarGalaxy::Models::Planet
      extend ScalarGalaxy::Internal::Type::RequestParameters::Converter
      include ScalarGalaxy::Internal::Type::RequestParameters

      def initialize: (?request_options: ScalarGalaxy::request_opts) -> void

      def to_hash: -> { request_options: ScalarGalaxy::RequestOptions }
    end
  end
end
