module ScalarGalaxy
  module Models
    type webhook_unwrap_params =
      {  } & ScalarGalaxy::Internal::Type::request_parameters

    class WebhookUnwrapParams < ScalarGalaxy::Internal::Type::BaseModel
      extend ScalarGalaxy::Internal::Type::RequestParameters::Converter
      include ScalarGalaxy::Internal::Type::RequestParameters

      def initialize: (?request_options: ScalarGalaxy::request_opts) -> void

      def to_hash: -> { request_options: ScalarGalaxy::RequestOptions }
    end
  end
end
