module ScalarGalaxy
  module Resources
    class Authentication
      def create_token: (
        email: String,
        password: String,
        ?request_options: ScalarGalaxy::request_opts
      ) -> ScalarGalaxy::Models::AuthenticationCreateTokenResponse

      def create_user: (
        email: String,
        password: String,
        ?name: String,
        ?request_options: ScalarGalaxy::request_opts
      ) -> ScalarGalaxy::User

      def list_me: (
        ?request_options: ScalarGalaxy::request_opts
      ) -> ScalarGalaxy::User

      def initialize: (client: ScalarGalaxy::Client) -> void
    end
  end
end
